export const GET_ALL_CATEGORY_REQUEST = "GET_ALL_CATEGORY_REQUEST";
export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";
export const GET_ALL_CATEGORY_FAILURE = "GET_ALL_CATEGORY_FAILURE";

export const GET_CATEGORIES_BY_SEARCH_TEXT_REQUEST =
  "GET_CATEGORIES_BY_SEARCH_TEXT_REQUEST";
export const GET_CATEGORIES_BY_SEARCH_TEXT_SUCCESS =
  "GET_CATEGORIES_BY_SEARCH_TEXT_SUCCESS";
export const GET_CATEGORIES_BY_SEARCH_TEXT_FAILURE =
  "GET_CATEGORIES_BY_SEARCH_TEXT_FAILURE";

export const UPDATE_TOP_LEVEL_CATEGORY_REQUEST = "UPDATE_TOP_LEVEL_CATEGORY_REQUEST";
export const UPDATE_TOP_LEVEL_CATEGORY_SUCCESS = "UPDATE_TOP_LEVEL_CATEGORY_SUCCESS";
export const UPDATE_TOP_LEVEL_CATEGORY_FAILURE = "UPDATE_TOP_LEVEL_CATEGORY_FAILURE";
export const UPDATE_SECOND_LEVEL_CATEGORY_REQUEST = "UPDATE_SECOND_LEVEL_CATEGORY_REQUEST";
export const UPDATE_SECOND_LEVEL_CATEGORY_SUCCESS = "UPDATE_SECOND_LEVEL_CATEGORY_SUCCESS";
export const UPDATE_SECOND_LEVEL_CATEGORY_FAILURE = "UPDATE_SECOND_LEVEL_CATEGORY_FAILURE";
export const UPDATE_THIRD_LEVEL_CATEGORY_REQUEST = "UPDATE_THIRD_LEVEL_CATEGORY_REQUEST";
export const UPDATE_THIRD_LEVEL_CATEGORY_SUCCESS = "UPDATE_THIRD_LEVEL_CATEGORY_SUCCESS";
export const UPDATE_THIRD_LEVEL_CATEGORY_FAILURE = "UPDATE_THIRD_LEVEL_CATEGORY_FAILURE";

// actionTypes.js

export const FETCH_TOP_LEVEL_CATEGORY_REQUEST = 'FETCH_TOP_LEVEL_CATEGORY_REQUEST';
export const FETCH_TOP_LEVEL_CATEGORY_SUCCESS = 'FETCH_TOP_LEVEL_CATEGORY_SUCCESS';
export const FETCH_TOP_LEVEL_CATEGORY_FAILURE = 'FETCH_TOP_LEVEL_CATEGORY_FAILURE';


export const RESET_CATEGORIES = "RESET_CATEGORIES";
