export const GET_ALL_FEATURES_REQUEST = "GET_ALL_FEATURES_REQUEST";
export const GET_ALL_FEATURES_SUCCESS = "GET_ALL_FEATURES_SUCCESS";
export const GET_ALL_FEATURES_FAILURE = "GET_ALL_FEATURES_FAILURE";